# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PetCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'PetCareTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'PetCare-tvOS' do
  target 'PetCare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
